##########################################################################
# Dockerfile for Tapis systems service
# This file must be placed in the build directory (api/target)
#   before docker build is run.
##########################################################################
FROM eclipse-temurin:17-jdk-jammy

MAINTAINER CIC Support <cicsupport@tacc.utexas.edu>

# Install less. Add user tapis
RUN apt update && apt install -y less vim-tiny && useradd -m tapis

USER tapis

WORKDIR /home/tapis/app

# Copy jar file into place
COPY --chown=tapis:tapis "systems.jar" .
COPY --chown=tapis:tapis "logback.xml" .
COPY --chown=tapis:tapis /dependencies dependencies

# Environment variables for testing without JWT
# ENV TAPIS_ENVONLY_ALLOW_TEST_HEADER_PARMS true
# ENV TAPIS_ENVONLY_JWT_OPTIONAL true
# ENV TAPIS_ENVONLY_SKIP_JWT_VERIFY true

# Other environment variables
ENV TAPIS_REQUEST_LOGGING_FILTER_PREFIXES /v3/systems

# Java module commands that are always needed (java 17 and later).
ENV JAVA_MODULE_OPTS --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.time=ALL-UNNAMED \
                     --add-opens java.base/java.util=ALL-UNNAMED

# Options for JVM
# Most options are for allowing jmx and remote debug access
# Option -Dp6spy.config.modulelist= is for turning off verbose SQL logging
ENV JAVA_TOOL_OPTIONS -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n \
                      -Djava.rmi.server.hostname=0.0.0.0 -Dcom.sun.management.jmxremote \
                      -Dcom.sun.management.jmxremote.port=9090  -Dcom.sun.management.jmxremote.rmi.port=9090 \
                      -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false \
                      -Dcom.sun.management.jmxremote.ssl=false \
                      -Dp6spy.config.modulelist=

# Server port, debug port and jmx port
EXPOSE 8080 8000 9090

CMD java -Xms4g -Xmx4g ${JAVA_MODULE_OPTS} -Dlogback.configurationFile=./logback.xml -cp "systems.jar:dependencies/*" \
    edu.utexas.tacc.tapis.systems.api.SystemsApplication
